on: [ workflow_dispatch ]

name: Manually triggered workflow

jobs:
  hello_job:
    name: Hello job
    runs-on: ubuntu-latest
    steps:
      - name: Print to console
        run: echo "Hello from the revitalize branch!"
