on:
  schedule:
    - cron: '40 16 * * *'

name: "[schedule] Update from API"

jobs:
  data_update:
    runs-on: ubuntu-latest
    name: Update data from API
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'revitalize'
          token: ${{ secrets.PAT_REPO }}
      - name: Update data from API
        uses: ./.github/actions/data-update
        with:
          github_pat: ${{ secrets.PAT_PUBLIC }}
          data_dir: /github/workspace/src/data
      - name: Commit & push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[AUTO] Update data."
          file_pattern: "src/data/*.json src/data/last_update"
